without cleaning , (duplicates) can lead to bias

In [5]:
import sqlite3
import pandas as pd
import os

In [36]:
db_path = os.path.join('database.sqlite')
connection = sqlite3.connect(db_path)

In [80]:
# loading dataset
df = pd.read_sql_query(  # not considering score = 3 (to avoid neutral ambiguity , only +ve and -ve)
"""
select *
from reviews
where score != 3 
order by ProductId
""", connection)
df.head(2)
df.tail(2)

            Id  ...                                               Text
525812    5703  ...  Purchased this product at a local store in NY ...
525813  327601  ...  I purchased this to send to my son who's away ...

[2 rows x 10 columns]

In [81]:
def partition(x):  # [1,2] => -ve , [4,5] => +ve
    if x < 3:    
        return 'negative'
    return 'positive'

score = df['Score']
positive_negative = score.map(partition)
df['Score'] = positive_negative

In [82]:
df.head()

       Id  ...                                               Text
0  150493  ...  These days, when a person says, "chicken soup"...
1  150494  ...  All of my children love this book.  My first g...
2  150496  ...  One of my earliest memories is of this book.  ...
3  150497  ...  I give five stars to the Maurice Sendak story....
4  150498  ...  This is a wonderful little book. I loved it 40...

[5 rows x 10 columns]

In [83]:
sorted_data = df.sort_values('ProductId', axis = 0, ascending=True, inplace=False)
sorted_data

            Id  ...                                               Text
0       150493  ...  These days, when a person says, "chicken soup"...
19      150513  ...  I remembered this book from my childhood and g...
20      150514  ...  It's a great book with adorable illustrations....
21      150515  ...  This book is a family favorite and was read to...
22      150516  ...  The same author wrote "Where the Wild Things A...
...        ...  ...                                                ...
525809  191721  ...  This coffee supposedly is premium, it tastes w...
525810    1478  ...  This coffee supposedly is premium, it tastes w...
525811  328482  ...  The basket was the perfect sympathy gift when ...
525812    5703  ...  Purchased this product at a local store in NY ...
525813  327601  ...  I purchased this to send to my son who's away ...

[525814 rows x 10 columns]

In [84]:
df2  =  sorted_data.drop_duplicates(subset={'UserId', 'ProfileName', 'Time', 'Summary', 'Text'})
df2

            Id  ...                                               Text
0       150493  ...  These days, when a person says, "chicken soup"...
19      150513  ...  I remembered this book from my childhood and g...
20      150514  ...  It's a great book with adorable illustrations....
21      150515  ...  This book is a family favorite and was read to...
22      150516  ...  The same author wrote "Where the Wild Things A...
...        ...  ...                                                ...
525782  193169  ...  I have been using this product for 4 months no...
525806  188389  ...  You have to try this sauce to believe it! It s...
525808  221795  ...  I bought this Hazelnut Paste (Nocciola Spread)...
525812    5703  ...  Purchased this product at a local store in NY ...
525813  327601  ...  I purchased this to send to my son who's away ...

[365333 rows x 10 columns]

In [85]:
(df2['Id'].size * 1.0) / (df['Id'].size * 1.0) * 100

69.4795117665182

In [86]:
display = pd.read_sql_query(
"""
SELECT *
FROM Reviews
WHERE Score != 3 AND Id= 544173 or Id = 64422
ORDER BY ProductId
""", connection)
display

       Id  ...                                               Text
0   64422  ...  My son loves spaghetti so I didn't hesitate or...
1  544173  ...  If you are looking for the secret ingredient i...

[2 rows x 10 columns]

In [87]:
final = df2[df2.HelpfulnessNumerator <= df2.HelpfulnessDenominator]

In [ ]:
print(final.shape)

final['Score'].value_counts()

(365331, 10)

Score
positive    307967
negative     57364
Name: count, dtype: int64

In [92]:
final.duplicated().sum()

np.int64(0)

In [93]:
final.isna().sum()

Id                        0
ProductId                 0
UserId                    0
ProfileName               0
HelpfulnessNumerator      0
HelpfulnessDenominator    0
Score                     0
Time                      0
Summary                   0
Text                      0
dtype: int64

In [97]:
final.describe()

                  Id  ...          Time
count  365331.000000  ...  3.653310e+05
mean   282791.666398  ...  1.296127e+09
std    164586.488829  ...  4.865088e+07
min         1.000000  ...  9.393408e+08
25%    140723.500000  ...  1.270858e+09
50%    278958.000000  ...  1.311379e+09
75%    428530.500000  ...  1.332893e+09
max    568454.000000  ...  1.351210e+09

[8 rows x 4 columns]

In [ ]:
#convert to csv 
final.to_csv("./reviews_clean_file")

In [101]:
df = pd.read_csv("./reviews_clean_file", index_col=0)

In [ ]:
df.info

In [103]:
df

            Id  ...                                               Text
0       150493  ...  These days, when a person says, "chicken soup"...
19      150513  ...  I remembered this book from my childhood and g...
20      150514  ...  It's a great book with adorable illustrations....
21      150515  ...  This book is a family favorite and was read to...
22      150516  ...  The same author wrote "Where the Wild Things A...
...        ...  ...                                                ...
525782  193169  ...  I have been using this product for 4 months no...
525806  188389  ...  You have to try this sauce to believe it! It s...
525808  221795  ...  I bought this Hazelnut Paste (Nocciola Spread)...
525812    5703  ...  Purchased this product at a local store in NY ...
525813  327601  ...  I purchased this to send to my son who's away ...

[365331 rows x 10 columns]